#! /bin/sh -x

# This should be called on system boot


############################
# Comment out this next line to enable this script
# exit 0 ############################


WAIT_1=1      # Wait before walking
WAIT_2=2
WAIT_3=150
WAIT_4=150



cd ~/aracna/RobotPi



sleep $WAIT_1

./walk.py -t 11 packing_slow

sleep $WAIT_2

./walk.py -t 22 star60_24
./walk.py -t 2 stand

sleep $WAIT_3

./walk.py -t 22 star6_2
./walk.py -t 2 stand

sleep $WAIT_4

./walk.py -t 22 star60_24
./walk.py -t 2 stand

sleep 300







echo "More walking"

./walk.py -t 20 star62
./walk.py -t 20 star62


echo "`date` About to call ./walk.py"
./walk.py gait1
./walk.py gait1
./walk.py gait1
echo "`date` Finished ./walk.py"

sleep $WAIT_3

echo "`date` About to call ./walk.py"
./walk.py wave
./walk.py wave
./walk.py wave
echo "`date` Finished ./walk.py"

















sleep $WAIT_1

echo "`date` About to call ./walk.py"
./walk.py swagger
./walk.py swagger
./walk.py swagger
echo "`date` Finished ./walk.py"

sleep $WAIT_2

echo "`date` About to call ./walk.py"
./walk.py gait1
./walk.py gait1
./walk.py gait1
echo "`date` Finished ./walk.py"

sleep $WAIT_3

echo "`date` About to call ./walk.py"
./walk.py wave
./walk.py wave
./walk.py wave
echo "`date` Finished ./walk.py"

sleep $WAIT_1

echo "`date` About to call ./walk.py"
./walk.py swagger
./walk.py swagger
./walk.py swagger
echo "`date` Finished ./walk.py"

sleep $WAIT_2

echo "`date` About to call ./walk.py"
./walk.py gait1
./walk.py gait1
./walk.py gait1
echo "`date` Finished ./walk.py"

sleep $WAIT_3

echo "`date` About to call ./walk.py"
./walk.py wave
./walk.py wave
./walk.py wave
echo "`date` Finished ./walk.py"

sleep $WAIT_1

echo "`date` About to call ./walk.py"
./walk.py swagger
./walk.py swagger
./walk.py swagger
echo "`date` Finished ./walk.py"

sleep $WAIT_2

echo "`date` About to call ./walk.py"
./walk.py gait1
./walk.py gait1
./walk.py gait1
echo "`date` Finished ./walk.py"

sleep $WAIT_3

echo "`date` About to call ./walk.py"
./walk.py wave
./walk.py wave
./walk.py wave
echo "`date` Finished ./walk.py"

sleep $WAIT_1

echo "`date` About to call ./walk.py"
./walk.py swagger
./walk.py swagger
./walk.py swagger
echo "`date` Finished ./walk.py"

sleep $WAIT_2

echo "`date` About to call ./walk.py"
./walk.py gait1
./walk.py gait1
./walk.py gait1
echo "`date` Finished ./walk.py"

sleep $WAIT_3

echo "`date` About to call ./walk.py"
./walk.py wave
./walk.py wave
./walk.py wave
echo "`date` Finished ./walk.py"

sleep $WAIT_1

echo "`date` About to call ./walk.py"
./walk.py swagger
./walk.py swagger
./walk.py swagger
echo "`date` Finished ./walk.py"

sleep $WAIT_2

echo "`date` About to call ./walk.py"
./walk.py gait1
./walk.py gait1
./walk.py gait1
echo "`date` Finished ./walk.py"

sleep $WAIT_3

echo "`date` About to call ./walk.py"
./walk.py wave
./walk.py wave
./walk.py wave
echo "`date` Finished ./walk.py"

sleep $WAIT_1

echo "`date` About to call ./walk.py"
./walk.py swagger
./walk.py swagger
./walk.py swagger
echo "`date` Finished ./walk.py"

sleep $WAIT_2

echo "`date` About to call ./walk.py"
./walk.py gait1
./walk.py gait1
./walk.py gait1
echo "`date` Finished ./walk.py"

sleep $WAIT_3

echo "`date` About to call ./walk.py"
./walk.py wave
./walk.py wave
./walk.py wave
echo "`date` Finished ./walk.py"

sleep $WAIT_1

echo "`date` About to call ./walk.py"
./walk.py swagger
./walk.py swagger
./walk.py swagger
echo "`date` Finished ./walk.py"

sleep $WAIT_2

echo "`date` About to call ./walk.py"
./walk.py gait1
./walk.py gait1
./walk.py gait1
echo "`date` Finished ./walk.py"

sleep $WAIT_3

echo "`date` About to call ./walk.py"
./walk.py wave
./walk.py wave
./walk.py wave
echo "`date` Finished ./walk.py"

sleep $WAIT_1

echo "`date` About to call ./walk.py"
./walk.py swagger
./walk.py swagger
./walk.py swagger
echo "`date` Finished ./walk.py"

sleep $WAIT_2

echo "`date` About to call ./walk.py"
./walk.py gait1
./walk.py gait1
./walk.py gait1
echo "`date` Finished ./walk.py"

sleep $WAIT_3

echo "`date` About to call ./walk.py"
./walk.py wave
./walk.py wave
./walk.py wave
echo "`date` Finished ./walk.py"

sleep $WAIT_1

echo "`date` About to call ./walk.py"
./walk.py swagger
./walk.py swagger
./walk.py swagger
echo "`date` Finished ./walk.py"

sleep $WAIT_2

echo "`date` About to call ./walk.py"
./walk.py gait1
./walk.py gait1
./walk.py gait1
echo "`date` Finished ./walk.py"

sleep $WAIT_3

echo "`date` About to call ./walk.py"
./walk.py wave
./walk.py wave
./walk.py wave
echo "`date` Finished ./walk.py"

sleep $WAIT_1

echo "`date` About to call ./walk.py"
./walk.py swagger
./walk.py swagger
./walk.py swagger
echo "`date` Finished ./walk.py"

sleep $WAIT_2

echo "`date` About to call ./walk.py"
./walk.py gait1
./walk.py gait1
./walk.py gait1
echo "`date` Finished ./walk.py"

sleep $WAIT_3

echo "`date` About to call ./walk.py"
./walk.py wave
./walk.py wave
./walk.py wave
echo "`date` Finished ./walk.py"

sleep $WAIT_1

echo "`date` About to call ./walk.py"
./walk.py swagger
./walk.py swagger
./walk.py swagger
echo "`date` Finished ./walk.py"

sleep $WAIT_2

echo "`date` About to call ./walk.py"
./walk.py gait1
./walk.py gait1
./walk.py gait1
echo "`date` Finished ./walk.py"

sleep $WAIT_3

echo "`date` About to call ./walk.py"
./walk.py wave
./walk.py wave
./walk.py wave
echo "`date` Finished ./walk.py"

sleep $WAIT_1

echo "`date` About to call ./walk.py"
./walk.py swagger
./walk.py swagger
./walk.py swagger
echo "`date` Finished ./walk.py"

sleep $WAIT_2

echo "`date` About to call ./walk.py"
./walk.py gait1
./walk.py gait1
./walk.py gait1
echo "`date` Finished ./walk.py"

sleep $WAIT_3

echo "`date` About to call ./walk.py"
./walk.py wave
./walk.py wave
./walk.py wave
echo "`date` Finished ./walk.py"

sleep $WAIT_1

echo "`date` About to call ./walk.py"
./walk.py swagger
./walk.py swagger
./walk.py swagger
echo "`date` Finished ./walk.py"

sleep $WAIT_2

echo "`date` About to call ./walk.py"
./walk.py gait1
./walk.py gait1
./walk.py gait1
echo "`date` Finished ./walk.py"

sleep $WAIT_3

echo "`date` About to call ./walk.py"
./walk.py wave
./walk.py wave
./walk.py wave
echo "`date` Finished ./walk.py"

sleep $WAIT_1

echo "`date` About to call ./walk.py"
./walk.py swagger
./walk.py swagger
./walk.py swagger
echo "`date` Finished ./walk.py"

sleep $WAIT_2

echo "`date` About to call ./walk.py"
./walk.py gait1
./walk.py gait1
./walk.py gait1
echo "`date` Finished ./walk.py"

sleep $WAIT_3

echo "`date` About to call ./walk.py"
./walk.py wave
./walk.py wave
./walk.py wave
echo "`date` Finished ./walk.py"

sleep $WAIT_1

echo "`date` About to call ./walk.py"
./walk.py swagger
./walk.py swagger
./walk.py swagger
echo "`date` Finished ./walk.py"

sleep $WAIT_2

echo "`date` About to call ./walk.py"
./walk.py gait1
./walk.py gait1
./walk.py gait1
echo "`date` Finished ./walk.py"

sleep $WAIT_3

echo "`date` About to call ./walk.py"
./walk.py wave
./walk.py wave
./walk.py wave
echo "`date` Finished ./walk.py"

sleep $WAIT_1

echo "`date` About to call ./walk.py"
./walk.py swagger
./walk.py swagger
./walk.py swagger
echo "`date` Finished ./walk.py"

sleep $WAIT_2

echo "`date` About to call ./walk.py"
./walk.py gait1
./walk.py gait1
./walk.py gait1
echo "`date` Finished ./walk.py"

sleep $WAIT_3

echo "`date` About to call ./walk.py"
./walk.py wave
./walk.py wave
./walk.py wave
echo "`date` Finished ./walk.py"

sleep $WAIT_1

echo "`date` About to call ./walk.py"
./walk.py swagger
./walk.py swagger
./walk.py swagger
echo "`date` Finished ./walk.py"

sleep $WAIT_2

echo "`date` About to call ./walk.py"
./walk.py gait1
./walk.py gait1
./walk.py gait1
echo "`date` Finished ./walk.py"

sleep $WAIT_3

echo "`date` About to call ./walk.py"
./walk.py wave
./walk.py wave
./walk.py wave
echo "`date` Finished ./walk.py"

sleep $WAIT_1

echo "`date` About to call ./walk.py"
./walk.py swagger
./walk.py swagger
./walk.py swagger
echo "`date` Finished ./walk.py"

sleep $WAIT_2

echo "`date` About to call ./walk.py"
./walk.py gait1
./walk.py gait1
./walk.py gait1
echo "`date` Finished ./walk.py"

sleep $WAIT_3

echo "`date` About to call ./walk.py"
./walk.py wave
./walk.py wave
./walk.py wave
echo "`date` Finished ./walk.py"

sleep $WAIT_1

echo "`date` About to call ./walk.py"
./walk.py swagger
./walk.py swagger
./walk.py swagger
echo "`date` Finished ./walk.py"

sleep $WAIT_2

echo "`date` About to call ./walk.py"
./walk.py gait1
./walk.py gait1
./walk.py gait1
echo "`date` Finished ./walk.py"

sleep $WAIT_3

echo "`date` About to call ./walk.py"
./walk.py wave
./walk.py wave
./walk.py wave
echo "`date` Finished ./walk.py"

sleep $WAIT_1

echo "`date` About to call ./walk.py"
./walk.py swagger
./walk.py swagger
./walk.py swagger
echo "`date` Finished ./walk.py"

sleep $WAIT_2

echo "`date` About to call ./walk.py"
./walk.py gait1
./walk.py gait1
./walk.py gait1
echo "`date` Finished ./walk.py"

sleep $WAIT_3

echo "`date` About to call ./walk.py"
./walk.py wave
./walk.py wave
./walk.py wave
echo "`date` Finished ./walk.py"

